name: Automatic build

on:
  push:
    branches: [ main, Dynamic-link ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install gcc libc-dev autoconf make automake libfuse3-dev libtool liblzma-dev zlib1g-dev libzstd-dev liblz4-dev liblzo2-dev
 
      - name: Build (x86_64)
        run: |
          sh build.sh
  
#      - name: Build (aarch64)
#        run: |
#          sh build-static.sh
  
      - name: Upload build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Monthly build"
          files: |
            squashfuse*
            libsquashfuse*
