name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2

    - name: Build for x86_64
      run: ./build.sh

    - name: Download Ubuntu aarch64
      run: wget https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-arm64.squashfs

    - name: Build for aarch64
      run: ./build_in_chroot.sh arm64
  
    - name: Upload build
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "nightly"
        prerelease: true
        title: "Nightly Build"
        files: |
          squashfuse*
          chroot/squashfuse*
