name: Automatic build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2

      - name: Setup latest Alpine Linux (x86_64)
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.16
          arch: x86_64
          shell-name: alpine-x86_64.sh
          packages: >
            autoconf
            git
            gcc
            automake
            make
            libc-dev
            fuse3-dev
            fuse3-static
            libtool
            zlib-dev
            xz-dev
            zstd-dev
            lz4-dev
            zlib-static
            zstd-static
            lz4-static
 
      # All non-x86 chips are emulated, thus VERY slow
      - name: Setup latest Alpine Linux (aarch64)
        uses: jirutka/setup-alpine@v1
        with:
          branch: v3.16
          arch: aarch64
          shell-name: alpine-aarch64.sh
          packages: >
            autoconf
            git
            gcc
            automake
            make
            libc-dev
            fuse3-dev
            fuse3-static
            libtool
            zlib-dev
            xz-dev
            zstd-dev
            lz4-dev
            zlib-static
            zstd-static
            lz4-static
 
      - name: Build (x86_64)
        run: |
          sh build-static.sh
        shell: alpine-x86_64.sh {0}
  
      - name: Build (aarch64)
        run: |
          sh build-static.sh
        shell: alpine-aarch64.sh {0}
  
      - name: Upload build
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          title: "Monthly build"
          files: |
            squashfuse*
            libsquashfuse*
